
pool:
  name: Hosted Ubuntu 1604
  demands: maven

steps:

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    dockerFile: src/Dockerfile
    imageName: 'Web:$(Build.BuildNumber)'
    includeLatestTag: true
    useDefaultContext: false
    buildContext: .
